version: "3.9"

networks:
  flashcards-net:

services:
  flashcards-db:
    image: postgres:14.5-alpine
    networks:
      - flashcards-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASS}
      PGDATA: /usr/share/data
    volumes:
      - "${DATA_DIR}/postgres:/usr/share/data:z"
