version: "3.9"

networks:
  flashcards-net:

services:
  flashcards-db:
    image: postgres:16.2-alpine
    networks:
      - flashcards-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASS}
      PGDATA: /usr/share/data
    volumes:
      - "${DATA_DIR}/postgres:/usr/share/data:z"

  flashcards-keycloak:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
      args:
        KEYCLOAK_INIT_REALM: "${KEYCLOAK_INIT_REALM}"
    networks:
      - flashcards-net
    depends_on:
      - flashcards-db
    ports:
      - "8081:8080"
      - "8082:9990"
    volumes:
      - "${DATA_DIR}/keycloak:/tmp"
    environment:
      KC_DB_URL: "${KEYCLOAK_DB_URL}"
      KC_DB_USERNAME: "${KEYCLOAK_DB_USER}"
      KC_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      DB_USER: "${KEYCLOAK_DB_USER}"
      DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      KC_HOSTNAME: "localhost"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    user: root

  flashcards-nats:
    image: nats:2.10.14-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: [ "CMD-SHELL", "netstat -an | grep 4222 | grep LISTEN" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - flashcards-net

  flashcards-tts-server:
    image: sszuev/open-tutor-tts-server:2.0.0-snapshot
    networks:
      - flashcards-net
    depends_on:
      flashcards-nats:
        condition: service_healthy
    environment:
      TTS_SERVER_NATS_HOST: "flashcards-nats"
      TTS_SERVICE_VOICERSS_KEY: "${TTS_SERVICE_VOICERSS_KEY}"

  flashcards-app:
    image: sszuev/open-tutor:2.0.0-snapshot
    networks:
      - flashcards-net
    ports:
      - "8080:8080"
    depends_on:
      - flashcards-tts-server
      - flashcards-keycloak
    environment:
      TTS_CLIENT_NATS_HOST: "flashcards-nats"
      KEYCLOAK_AUTHORIZE_ADDRESS: "http://localhost:8081"
      KEYCLOAK_ACCESS_TOKEN_ADDRESS: "http://flashcards-keycloak:8080"
      DB_PG_URL: "jdbc:postgresql://flashcards-db:5432/postgres"
      DB_PG_USER: ${POSTGRES_DEFAULT_USER}
      DB_PG_PWD: ${POSTGRES_DEFAULT_PASS}
      PORT: 8080