version: "3.9"

networks:
  flashcards-net:

services:
  flashcards-db:
    image: postgres:16.2-alpine
    networks:
      - flashcards-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASS}
      PGDATA: /usr/share/data
    volumes:
      - "${DATA_DIR}/postgres:/usr/share/data:z"

  flashcards-keycloak:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
      args:
        KEYCLOAK_INIT_REALM: "${KEYCLOAK_INIT_REALM}"
    networks:
      - flashcards-net
    depends_on:
      - flashcards-db
    ports:
      - "8081:8080"
      - "8082:9990"
    volumes:
      - "${DATA_DIR}/keycloak:/tmp"
    environment:
      KC_DB_URL: "${KEYCLOAK_DB_URL}"
      KC_DB_USERNAME: "${KEYCLOAK_DB_USER}"
      KC_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      DB_USER: "${KEYCLOAK_DB_USER}"
      DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      KC_HOSTNAME: "localhost"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    user: root

  flashcards-rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - flashcards-net
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - "${DATA_DIR}/rabbitmq/data/:/var/lib/rabbitmq:z"
      - "${DATA_DIR}/rabbitmq/log/:/var/log/rabbitmq:z"

  flashcards-tts-server:
    image: sszuev/open-tutor-tts-server:2.0.0-snapshot
    networks:
      - flashcards-net
    depends_on:
      flashcards-rabbitmq:
        condition: service_healthy
    environment:
      TTS_SERVER_RABBITMQ_HOST: "flashcards-rabbitmq"
      TTS_SERVICE_VOICERSS_KEY: "${TTS_SERVICE_VOICERSS_KEY}"