version: '3.9'

networks:
  flashcards-net:

services:
  db:
    image: postgres:14.5-alpine
    networks:
      - flashcards-net
    container_name: flashcards-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASS}
      PGDATA: /usr/share/data
    volumes:
      - "${DATA_DIR}:/usr/share/data:z"
