## Examples of requests for cards api (V1, stub-mode)

### Create Card Success
POST http://localhost:8080/v1/api/cards/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "createCard",
  "requestId": "createCardSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "card": {
    "cardId": "42",
    "dictionaryId": "100500",
    "word": "anticyclone",
    "transcription": "æntɪˈsaɪkləʊn",
    "partOfSpeech": "noun",
    "translations": [
      [
        "антициклон"
      ]
    ],
    "examples": [
    ],
    "sound": null,
    "answered": 42,
    "details": {
      "A": 2,
      "B": 3
    }
  }
}

### Create Card Error
POST http://localhost:8080/v1/api/cards/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "createCard",
  "requestId": "createCardError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  },
  "card": {
    "cardId": "42",
    "dictionaryId": "100500",
    "word": "weather",
    "transcription": "ˈweðə",
    "partOfSpeech": "verb",
    "translations": [
      [
        "погода"
      ]
    ],
    "examples": [
      "We're seeing some bad weather over Canaveral."
    ],
    "sound": "/audio/en-ru-weather.wav",
    "answered": 42,
    "details": {
      "C": 2,
      "D": 3
    }
  }
}

### Update Card Success
POST http://localhost:8080/v1/api/cards/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "updateCard",
  "requestId": "updateCardSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "card": {
    "cardId": "42",
    "dictionaryId": "100500",
    "word": "word",
    "transcription": "word",
    "partOfSpeech": "adjective",
    "translations": [
      [
        "слово"
      ]
    ]
  }
}

### Update Card Error
POST http://localhost:8080/v1/api/cards/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "updateCard",
  "requestId": "updateCardError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  },
  "card": {
    "cardId": "42",
    "dictionaryId": "100500",
    "word": "world",
    "transcription": "wɜːld",
    "partOfSpeech": "noun",
    "translations": [
      [
        "мир"
      ]
    ]
  }
}

### Search Cards Success
POST http://localhost:8080/v1/api/cards/search
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "searchCards",
  "requestId": "getCardsSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "random": true,
  "unknown": true,
  "length": 42,
  "dictionaryIds": [
    "100500",
    "4200",
    "420",
    "42",
    "4",
    "2"
  ]
}

### Search Cards Error
POST http://localhost:8080/v1/api/cards/search
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "searchCards",
  "requestId": "getCardsError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  },
  "random": false,
  "unknown": false,
  "length": 2,
  "dictionaryIds": [
    "42"
  ]
}

### Get All Cards Success
POST http://localhost:8080/v1/api/cards/get-all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getAllCards",
  "requestId": "getAllCardsSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "dictionaryId": "1"
}

### Get All Cards Error
POST http://localhost:8080/v1/api/cards/get-all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getAllCards",
  "requestId": "getAllCardsError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  },
  "dictionaryId": "-1"
}

### Get Card Success
POST http://localhost:8080/v1/api/cards/get
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getCard",
  "requestId": "getCardSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "cardId": "card-42"
}

### Get Card Error
POST http://localhost:8080/v1/api/cards/get
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getCard",
  "requestId": "getCardError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  },
  "cardId": "card-42"
}

### Learn Card Success
POST http://localhost:8080/v1/api/cards/learn
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "learnCard",
  "requestId": "learnCardSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "cards": [
    {
      "cardId": "42",
      "details": {
        "A": 2,
        "B": 3
      }
    }
  ]
}

### Learn Card Success
POST http://localhost:8080/v1/api/cards/learn
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "learnCard",
  "requestId": "learnCardError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  },
  "cards": [
    {
      "cardId": "42",
      "details": {
        "a": 1,
        "b": 2
      }
    }
  ]
}

### Reset Card Success
POST http://localhost:8080/v1/api/cards/reset
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "cardId": "42",
  "requestType": "resetCard",
  "requestId": "resetCardSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

### Reset Card Error
POST http://localhost:8080/v1/api/cards/reset
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "cardId": "42",
  "requestType": "resetCard",
  "requestId": "resetCardError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  }
}

### Delete Card Success
POST http://localhost:8080/v1/api/cards/delete
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "cardId": "42",
  "requestType": "deleteCard",
  "requestId": "deleteCardSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

### Delete Card Error
POST http://localhost:8080/v1/api/cards/delete
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "cardId": "42",
  "requestType": "deleteCard",
  "requestId": "deleteCardError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  }
}

### Get sound success
POST http://localhost:8080/v1/api/sounds/get
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getAudio",
  "requestId": "getSoundSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "lang": "EN",
  "word": "snow"
}

### Get sound server error
POST http://localhost:8080/v1/api/sounds/get
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getAudio",
  "requestId": "getSoundError",
  "debug": {
    "mode": "stub",
    "stub": "error_audio_resource_server_error"
  },
  "lang": "EN",
  "word": "snow"
}