CREATE TABLE public.users (
    id bigint NOT NULL,
    uuid UUID NOT NULL UNIQUE,
    details JSON NOT NULL DEFAULT '{}'::JSON,
    changed_at TIMESTAMP NOT NULL DEFAULT now()::TIMESTAMP
);

CREATE TABLE public.dictionaries (
    id BIGINT NOT NULL,
    name VARCHAR(1024) NOT NULL,
    user_id bigint NOT NULL,
    target_lang VARCHAR(42) NOT NULL,
    source_lang VARCHAR(42) NOT NULL,
    details JSON NOT NULL DEFAULT '{}'::JSON,
    changed_at TIMESTAMP NOT NULL DEFAULT now()::TIMESTAMP
);

CREATE TABLE public.cards (
    id BIGINT NOT NULL,
    dictionary_id BIGINT NOT NULL,
    words JSONB NOT NULL DEFAULT '{}'::JSONB,
    answered INTEGER,
    details JSON NOT NULL DEFAULT '{}'::JSON,
    changed_at TIMESTAMP NOT NULL DEFAULT now()::TIMESTAMP
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.dictionaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dictionaries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.dictionaries
    ADD CONSTRAINT dictionaries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.dictionaries
    ADD CONSTRAINT fk_dictionaries_users_id FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT fk_cards_dictionaries_id FOREIGN KEY (dictionary_id) REFERENCES public.dictionaries(id);