## Examples of requests for dictionaries api (V1, stub-mode)

### Get alldictionaries success
POST http://localhost:8080/v1/api/dictionaries/get-all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getAllDictionaries",
  "requestId": "getDictionariesSuccess",
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

### Get alldictionaries error
POST http://localhost:8080/v1/api/dictionaries/get-all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWE0MTRmNS0zZjc1LTQ0OTQtYjY2NC1mNGM4YjMzZmY0ZTYiLCJhdWQiOiJmbGFzaGNhcmRzLWF1ZGllbmNlIiwiaXNzIjoiZmxhc2hjYXJkcy1pc3N1ZXIifQ.rz5NpLQK7rJvr-ROCOw0giAU-mgRCZPmm8nLiU2rrr8

{
  "requestType": "getAllDictionaries",
  "requestId": "getDictionariesUnknownError",
  "debug": {
    "mode": "stub",
    "stub": "error_unknown"
  }
}
