package com.github.sszuev.flashcards.android

const val STAGE_SHOW_BUTTONS_DELAY_MS = 500L
const val STAGE_MOSAIC_CELL_DELAY_MS = 500L
const val STAGE_OPTIONS_CELL_DELAY_MS = 500L
const val STAGE_WRITING_BUTTONS_DELAY_MS = 500L

const val PLAY_AUDIO_EMERGENCY_TIMEOUT_MS = 10_000L

const val STAGE_WRITING_PREFIX_LENGTH = 3

const val CELL_TEXT_LIMIT = 22